### ISSUE TITLE
Visual glitches and sound distorsions

### ISSUE THREAD

**Issue by M100o000** [simple64/simple64#422] opened 2024-04-06 02:06 UTC
Visual glitches

Don't now just dowloaded the emulator and i download
it again and the same thing happend

Expeceted behavior normal screen

![Zelda Oot visual glitch](https://github.com/simple64/simple64/assets/165270595/6c0f92c7-ee3a-4e68-abb8-cebead1142ce)

![Zelda Oot visual glitch 2](https://github.com/simple64/simple64/assets/165270595/04b28cd9-7c3c-4fcb-964b-adbd6172bb2f)

![Zelda Oot visual glitch 3](https://github.com/simple64/simple64/assets/165270595/65533f46-3093-45ef-96ae-09fae51ef8fb)

![Majoramaskglicht](https://github.com/simple64/simple64/assets/165270595/d81f0c8c-4684-4075-adfd-2cfc866ba257)

Os windows 10

and

**Comment by loganmc10** [comment] 2024-04-06 02:11
Duplicate of #402

**Closed by loganmc10** 2024-04-06 02:11 UTC
