### ISSUE TITLE
Problem with emulator!

### ISSUE THREAD

**Issue by MoosecianImmerse** [simple64/simple64#411] opened 2024-01-05 14:25 UTC
![Capture](https://github.com/simple64/simple64/assets/132798005/0bc1ebcf-dade-4bd4-b7ca-c9c99b71d137)
This is the glitchy screen I get when I use the emulator. How do I fix this?

**Comment by MasterNama17083** [comment] 2024-01-07 14:46
Same. Previously, I made an issue at #402

**Comment by M100o000** [comment] 2024-04-06 02:09
#422  is same

**Comment by loganmc10** [comment] 2024-04-06 02:11
Duplicate of #402

**Closed by loganmc10** 2024-04-06 02:11 UTC
