### ISSUE TITLE
I ask to Add Changeable Fast Forward Hotkey.

### ISSUE THREAD

**Issue by Khechari-Mudra** [simple64/simple64#353] opened 2023-02-04 20:40 UTC
I use Fedora 37 x64. Flathub Simple64 Emulator.

I want to use spacebar as Fast Forward.

I ask to Change Hotkey to be possible in this Emulator,in GUI.

Thanks in Advanced.

**Comment by loganmc10** [comment] 2023-04-01 01:54
Duplicate of https://github.com/simple64/simple64/issues/314

**Closed by loganmc10** 2023-04-01 01:54 UTC
