### ISSUE TITLE
Cached interpreter issues on CBFD

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [simple64/simple64#267] opened 2022-07-18 22:51 UTC
**Describe the bug**

- Conker's Bad Fur Day randomly soft freeze with the cached interpreter and shows this error:
```
Core: Initializing 4 RDRAM modules for a total of 8 MB
Core: Starting R4300 emulator: Cached Interpreter
Video: vdac_write: resized framebuffer texture: 285x213
Core Warning: Unknown PI DMA write: 0x1000 -> 0xFFFE (0x100000)
Core Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.
```

**Expected behavior**

- No random freezes on CBFD with the cached interpreter

**Desktop 1:**

 - OS: Xubuntu
 - Version: 16.04.7 LTS
 - GPU: Radeon RX 560 Series (POLARIS11)
 - Audio: "VIA VT1708S" ( _Advanced Micro Devices, Inc. [AMD/ATI] SBx00 Azalia (Intel HDA)_ )

**Desktop 2:**

 - OS: Windows 10 Pro
 - Version: 21H2 - 19044.1889
 - GPU: NVIDIA Quadro K620
 - Audio: Realtek High Definition Audio

**Additional context**

The testing on Xubuntu was performed with the **UI Console**.

Using:
* https://github.com/simple64/mupen64plus-core/commit/116e303da6d294d40ca15b5a8f927008e44fe029
* https://github.com/ata4/angrylion-rdp-plus/commit/7ff7ae7df69e559aa3c39f71dd9a9b2ffe37a7b2
* https://github.com/simple64/parallel-rsp/commit/b2933221c36fd63a77bded0d4e29b882a4407305

The testing on Windows 10 Pro was performed with [830e68d](https://github.com/simple64/simple64/tree/v2022.09.2).

**P.S: The pure interpreter works perfectly fine in both cases.**

**Comment by loganmc10** [comment] 2022-07-19 00:49
I can't reproduce the issues with Perfect Dark or Conkers, although I am still tweaking the core timing a bit.

The randomize interrupt issue is because the PI interrupts are no longer random, I'll have to think of a better way to address this.

I only test m64p with parallel-rdp, parallel-rsp, audio-sdl2, and mupen64plus-gui, bug reports for other configurations don't belong here.

**Comment by loganmc10** [comment] 2022-07-19 01:20
Actually, Conkers is an interesting case. I normally test these games on fast forward so that I can save time. Conkers isn't freezing, it's just staying at one screen for a very long time (if you fast forward you'll get past).

It just requires really specific timing I think, I'll be lowering the SI DMA timing in the next release which I think will help

**Comment by loganmc10** [comment] 2022-07-19 01:31
Also just to clarify the other point: upstream mupen64plus is essentially unmaintained. There is a lot of work that would need to happen in order to make these changes compatible with the dynarecs, which I don't plan on doing. So it's unlikely these changes will get merged into upstream mupen64plus anytime soon (unless someone takes on that work).

I'm only concerned with compatibility within this project, bugs related to other plugins that exist should go somewhere else.

**Comment by Jj0YzL5nvJ** [comment] 2022-07-19 09:10
I'm aware of all that, good to know that you can't reproduce the audio issue. I need to upgrade my distro urgently, but I don't have a strong enough incentives... yet.
I will try to only report problems that are potentially reproducible on m64p.

**Comment by loganmc10** [comment] 2022-07-19 17:35
randomization should be fixed in https://github.com/m64p/m64p/releases/tag/v2022.07.8, i'd be curious if conkers and perfect dark work any better as well

**Comment by loganmc10** [comment] 2022-08-06 14:59
I think all these issues are solved @Jj0YzL5nvJ ? Do you know if any of these are still happening?

**Comment by Jj0YzL5nvJ** [comment] 2022-08-07 18:09
CBFD breaks randomly in unexpectedly ways, sometimes it freezes, sometimes the camera rotates out of control and resets its position in an infinite loop, sometimes the "double jump" stops working at crucial moments... it's unplayable.
That happened with yesterday's build, I will try with today's.

**Comment by Jj0YzL5nvJ** [comment] 2022-08-21 03:50
I can no longer reproduce the previous audio interruptions. Now I can reproduce an error similar to what I saw using ParaLLEl RDP on Win10 Pro.
```
Core Warning: Unknown PI DMA write: 0x1000 -> 0xFFFE (0x100000)
```

**Comment by DarthSidious666** [comment] 2022-08-24 15:30
Can you retry with the current build?

**Comment by Jj0YzL5nvJ** [comment] 2022-08-27 18:59
This CBFD issue is strangely similar to [INDY in upstream...](https://github.com/mupen64plus/mupen64plus-core/issues/949#issuecomment-1114867812)

**Comment by DarthSidious666** [comment] 2022-08-30 09:05
It could be the cached interpreter, I believe I've found a bug with it while testing and Logan has confirmed there is an issue with the cached interpreter so he's going to look into it.

Could you try with the Pure Interpreter and see if it happens with that?

**Comment by loganmc10** [comment] 2023-04-26 20:12
I'm going to close this in favour of https://github.com/simple64/simple64/issues/351

**Closed by loganmc10** 2023-04-26 20:12 UTC
Labels: need more info
