### ISSUE TITLE
Conkler

### ISSUE THREAD

**Issue by fatboivonspit** [simple64/simple64#438] opened 2024-06-24 02:25 UTC
**Describe the bug**
While playing it will randomly freeze.

**To Reproduce**
It just happens randomly.

**Desktop (please complete the following information):**
Windows 11
GeForce RTX 3060

**Additional context**

**Comment by loganmc10** [comment] 2024-06-24 02:31
Duplicate of https://github.com/simple64/simple64/issues/379

**Closed by loganmc10** 2024-06-24 02:31 UTC
